version: '2.4'
services:
  django:
    restart: always
    container_name: django
    build:
      context: ./backend
    volumes:
      - ./backend/:/home/campaign/backend
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - '8000'
    depends_on:
      - postgres
      - redis
    env_file:
      - ./backend/.env
  nginx:
    restart: always
    container_name: nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/static/:/home/campaign/backend/static
      - ./backend/media/:/home/campaign/backend/media
      - ./backend/staticfiles/:/home/campaign/backend/staticfiles
    depends_on:
      - django
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
  redis:
    container_name: redis
    restart: always
    image: redis
    ports:
      - '6379:6379'