services:
  django:
    restart: always
    container_name: django
    build:
      context: ./backend
    volumes:
      - ./backend/:/home/campaign/backend
      - ./cert/:/home/campaign
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn -c conf/gunicorn_conf.py core.wsgi:application"
    expose:
      - '8000'
    depends_on:
      - postgres
      - redis
    env_file:
      - ./docker.env
  celery_worker:
    container_name: celery_worker
    build:
      context: ./backend
    command: celery -A core worker --loglevel=info
    volumes:
      - ./backend/:/home/campaign/backend
    depends_on:
      - redis
      - django
    env_file:
      - ./docker.env
  nginx:
    restart: always
    container_name: nginx
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cert/:/home/campaign
      - ./backend/media/:/home/campaign/backend/media
      - ./backend/staticfiles/:/home/campaign/backend/staticfiles
      - /home/whatsapp-partners/backend/static/:/home/whatsapp/backend/static
      - /home/whatsapp-partners/backend/media/:/home/whatsapp/backend/media
      - /home/whatsapp-partners/backend/staticfiles/:/home/whatsapp/backend/staticfiles
    depends_on:
      - django
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./docker.env
    environment:
      - POSTGRES_DB=${DB_NAME:-campaignMakerDB}
      - POSTGRES_USER=${DB_USER:-campaignMakerAdmin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-aRZXFK0VVNtW817}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: redis
    restart: always
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  memcached:
    image: memcached
    container_name: memcached
    ports:
      - "11211:11211"
    restart: always


volumes:
  postgres_data: