# Generated by Django 4.2.5 on 2023-09-17 05:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaignemailtype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsmstype',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, blank=True, editable=True, populate_from='name', unique=True, verbose_name='Safe URL'),
        ),
        migrations.AlterField(
            model_name='campaigntype',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, blank=True, editable=True, populate_from='name', unique=True, verbose_name='Safe URL'),
        ),
        migrations.AlterField(
            model_name='campaignzip',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, blank=True, editable=True, populate_from='name', unique=True, verbose_name='Safe URL'),
        ),
    ]
