# Generated by Django 4.2.5 on 2023-09-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Name'),
        ),
    ]
